# Generated by Django 4.2.6 on 2023-10-20 04:38

from django.db import migrations, models
import files.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SavedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Název souboru')),
                ('file_type', models.CharField(blank=True, max_length=255, null=True, verbose_name='Typ souboru')),
                ('file_size', models.IntegerField(blank=True, null=True, verbose_name='Velikost souboru')),
                ('file', models.FileField(blank=True, null=True, upload_to=files.models.file_directory_path, verbose_name='Soubor')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='Čas nahrání')),
            ],
            options={
                'verbose_name': 'File',
                'verbose_name_plural': 'Files',
            },
        ),
    ]
